if(NOT CORESIM_SANITIZER MATCHES "^(none|address|thread)$")
    message(FATAL_ERROR "CORESIM_SANITIZER must be none, address, or thread")
endif()
function(coresim_target_options target)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
        if(CORESIM_SANITIZER STREQUAL "address")
            target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address,undefined)
        elseif(CORESIM_SANITIZER STREQUAL "thread")
            target_compile_options(${target} PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=thread)
        endif()
    elseif(NOT CORESIM_SANITIZER STREQUAL "none")
        message(FATAL_ERROR "Sanitizers require GCC or Clang")
    endif()
endfunction()
